<?php
return array (
  'PhlyComic\\FetchController' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'FetchController.php',
  'PhlyComic\\Comic' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'Comic.php',
  'PhlyComic\\ComicDescription' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicDescription.php',
  'PhlyComic\\ComicSource\\ReptilisRex' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'ReptilisRex.php',
  'PhlyComic\\ComicSource\\GarfieldMinusGarfield' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'GarfieldMinusGarfield.php',
  'PhlyComic\\ComicSource\\GoComics' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'GoComics.php',
  'PhlyComic\\ComicSource\\ForBetterOrForWorse' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'ForBetterOrForWorse.php',
  'PhlyComic\\ComicSource\\ScenesFromAMultiverse' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'ScenesFromAMultiverse.php',
  'PhlyComic\\ComicSource\\PennyArcade' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'PennyArcade.php',
  'PhlyComic\\ComicSource\\Xkcd' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'Xkcd.php',
  'PhlyComic\\ComicSource\\AbstractComicSource' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'AbstractComicSource.php',
  'PhlyComic\\ComicSource\\AbstractDomSource' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'AbstractDomSource.php',
  'PhlyComic\\ComicSource\\AbstractRssSource' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'AbstractRssSource.php',
  'PhlyComic\\ComicSource\\NotInventedHere' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'NotInventedHere.php',
  'PhlyComic\\ComicSource\\Dilbert' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'Dilbert.php',
  'PhlyComic\\ComicSource\\FoxTrot' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'FoxTrot.php',
  'PhlyComic\\ComicSource\\UserFriendly' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'UserFriendly.php',
  'PhlyComic\\ComicSource\\BasicInstructions' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'BasicInstructions.php',
  'PhlyComic\\ComicSource\\CtrlAltDel' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource' . DIRECTORY_SEPARATOR . 'CtrlAltDel.php',
  'PhlyComic\\ComicSource' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicSource.php',
  'PhlyComic\\ComicFactory' => __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'PhlyComic' . DIRECTORY_SEPARATOR . 'ComicFactory.php',
);
